/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Role;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class RaillineAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RaillineAdminWorkAreaJPanel
     */
    private JPanel mainScreen;
    private UserAccount userAccount;
    private EcoSystem system;
    public RaillineAdminWorkAreaJPanel(JPanel mainScreen, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.mainScreen = mainScreen;
        this.userAccount = userAccount;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageTrain = new javax.swing.JButton();
        btnManageRailNumber = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("BM Hanna 11yrs Old", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 102));
        jLabel1.setText("——Welcome to Rail Company");

        btnManageTrain.setBackground(new java.awt.Color(104, 139, 241));
        btnManageTrain.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnManageTrain.setText("Manage Train");
        btnManageTrain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTrainActionPerformed(evt);
            }
        });

        btnManageRailNumber.setBackground(new java.awt.Color(104, 139, 241));
        btnManageRailNumber.setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N
        btnManageRailNumber.setText("Manage RailNumber");
        btnManageRailNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageRailNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRailNumberActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(104, 139, 241));
        jButton3.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        jButton3.setText("Manage Rail Crew");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageRailNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageRailNumber, btnManageTrain, jButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addComponent(btnManageRailNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnManageTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnManageRailNumber, btnManageTrain, jButton3});

    }// </editor-fold>//GEN-END:initComponents

    private void btnManageTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTrainActionPerformed
        // TODO add your handling code here:
        ManageTrainJPanel majp = new ManageTrainJPanel(mainScreen, userAccount, system);
        mainScreen.add("ManageTrainJPanel", majp);
        CardLayout layout = (CardLayout) mainScreen.getLayout();
        layout.next(mainScreen);
    }//GEN-LAST:event_btnManageTrainActionPerformed

    private void btnManageRailNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRailNumberActionPerformed
        // TODO add your handling code here:
        ManageRailNumberJPanel mfjp = new ManageRailNumberJPanel(mainScreen, userAccount, system);
        mainScreen.add("ManageRailNumberJPanel", mfjp);
        CardLayout layout = (CardLayout) mainScreen.getLayout();
        layout.next(mainScreen);
    }//GEN-LAST:event_btnManageRailNumberActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ManageRailCrewJPanel macjp = new ManageRailCrewJPanel(mainScreen, userAccount, system);
        mainScreen.add("ManageRailCrewJPanel", macjp);
        CardLayout layout = (CardLayout) mainScreen.getLayout();
        layout.next(mainScreen);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageRailNumber;
    private javax.swing.JButton btnManageTrain;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
